using AlasApp.Application.Abstractions.Messaging;
using AlasApp.Application.Abstractions.Services;
using AlasApp.Application.Articles.Commands.CreateArticle;
using AlasApp.Application.Articles.Commands.DeleteArticle;
using AlasApp.Application.Articles.Commands.UpdateArticle;
using AlasApp.Application.Articles.Queries.GetArticleBySlug;
using AlasApp.Application.Articles.Queries.ListArticles;
using AlasApp.Application.AdminSettings.Commands.TestIntegration;
using AlasApp.Application.AdminSettings.Commands.UpdateAdminSettings;
using AlasApp.Application.AdminSettings.Queries.GetAdminSettings;
using AlasApp.Application.AdminUsers.Commands.CreateAdminUser;
using AlasApp.Application.AdminUsers.Commands.DeleteAdminUser;
using AlasApp.Application.AdminUsers.Commands.UpdateAdminUser;
using AlasApp.Application.AdminUsers.Queries.GetAdminUserById;
using AlasApp.Application.AdminUsers.Queries.ListAdminRoles;
using AlasApp.Application.AdminUsers.Queries.ListAdminUsers;
using AlasApp.Application.Auth.Commands.ConfirmPasswordReset;
using AlasApp.Application.Auth.Commands.ChangeUserPassword;
using AlasApp.Application.Auth.Commands.LoginUser;
using AlasApp.Application.Auth.Commands.LogoutUser;
using AlasApp.Application.Auth.Commands.RegisterUser;
using AlasApp.Application.Auth.Commands.RequestPasswordReset;
using AlasApp.Application.Categories.Commands.CreateCategory;
using AlasApp.Application.Categories.Commands.DeleteCategory;
using AlasApp.Application.Categories.Commands.ImportCategories;
using AlasApp.Application.Categories.Commands.UpdateCategory;
using AlasApp.Application.Categories.Queries.GetCategoryById;
using AlasApp.Application.Categories.Queries.ListCategories;
using AlasApp.Application.CategoryTariffs.Commands.UpsertCategoryTariff;
using AlasApp.Application.CategoryTariffs.Queries.GetCategoryTariffs;
using AlasApp.Application.Competitors.Commands.CreateCompetitor;
using AlasApp.Application.Competitors.Commands.DeleteCompetitor;
using AlasApp.Application.Competitors.Commands.UpdateCompetitorLicense;
using AlasApp.Application.Competitors.Commands.UpdateCompetitorNotifications;
using AlasApp.Application.Competitors.Commands.UpdateCompetitor;
using AlasApp.Application.Competitors.Queries.GetCompetitorCalendar;
using AlasApp.Application.Competitors.Queries.GetCompetitorById;
using AlasApp.Application.Competitors.Queries.GetCompetitorInscriptions;
using AlasApp.Application.Competitors.Queries.GetCompetitorNotifications;
using AlasApp.Application.Competitors.Queries.GetCompetitorPointsHistory;
using AlasApp.Application.Competitors.Queries.ListCompetitors;
using AlasApp.Application.Circuits.Commands.CreateCircuit;
using AlasApp.Application.Circuits.Commands.DeleteCircuit;
using AlasApp.Application.Circuits.Commands.ImportCircuits;
using AlasApp.Application.Circuits.Commands.UpdateCircuit;
using AlasApp.Application.Circuits.Queries.GetCircuitById;
using AlasApp.Application.Circuits.Queries.ListCircuits;
using AlasApp.Application.Dashboard.Queries.GetDashboard;
using AlasApp.Application.CompetitorFines.Commands.CreateCompetitorFine;
using AlasApp.Application.CompetitorFines.Commands.UpdateCompetitorFine;
using AlasApp.Application.CompetitorFines.Queries.ListCompetitorFines;
using AlasApp.Application.EventCategories.Commands.UpdateEventCategories;
using AlasApp.Application.EventCategories.Queries.GetEventCategories;
using AlasApp.Application.EventResults;
using AlasApp.Application.EventResults.Commands.ImportEventResults;
using AlasApp.Application.EventResults.Commands.UpsertEventResults;
using AlasApp.Application.EventResults.Queries.GetEventResults;
using AlasApp.Application.EventResults.Queries.GetEventResultsRoster;
using AlasApp.Application.EventResults.Queries.GetPrizeDistribution;
using AlasApp.Application.Galleries.Queries.GetGalleryBySlug;
using AlasApp.Application.Galleries.Queries.ListGalleries;
using AlasApp.Application.Events.Commands.CreateEvent;
using AlasApp.Application.Events.Commands.DeleteEvent;
using AlasApp.Application.Events.Commands.ImportEvents;
using AlasApp.Application.Events.Commands.UpdateEvent;
using AlasApp.Application.Events.Queries.GetEventById;
using AlasApp.Application.Events.Queries.ListEvents;
using AlasApp.Application.Live.Queries.GetPublicLiveStatus;
using AlasApp.Application.PublicSiteSettings.Queries.GetPublicSiteSettings;
using AlasApp.Application.Inscriptions.Commands.CreateInscription;
using AlasApp.Application.Inscriptions.Commands.DeleteInscription;
using AlasApp.Application.Inscriptions.Commands.UpdateInscription;
using AlasApp.Application.Inscriptions.Queries.GetInscriptionById;
using AlasApp.Application.Inscriptions.Queries.ListInscriptions;
using AlasApp.Application.Memberships.Commands.CreateMembership;
using AlasApp.Application.Memberships.Commands.DeleteMembership;
using AlasApp.Application.Memberships.Commands.UpdateMembership;
using AlasApp.Application.Memberships.Queries.GetMembershipById;
using AlasApp.Application.Memberships.Queries.ListMemberships;
using AlasApp.Application.Payments.Commands.ApproveBeachToken;
using AlasApp.Application.Payments.Commands.CapturePayPalOrder;
using AlasApp.Application.Payments.Commands.CreatePayment;
using AlasApp.Application.Payments.Commands.InitiatePayPalOrder;
using AlasApp.Application.Payments.Commands.RejectBeachToken;
using AlasApp.Application.Payments.Commands.RequestBeachToken;
using AlasApp.Application.Payments.Commands.RedeemBeachToken;
using AlasApp.Application.Payments.Commands.UpdatePayment;
using AlasApp.Application.Payments.Queries.GetPaymentById;
using AlasApp.Application.Payments.Queries.GetPaymentKpis;
using AlasApp.Application.Payments.Queries.ListBeachTokens;
using AlasApp.Application.Payments.Queries.ListPayments;
using AlasApp.Application.Rankings.Commands.SyncSurfScoresCircuit;
using AlasApp.Application.Rankings.Queries.GetRanking;
using AlasApp.Application.Rankings.Queries.ListRankingCategories;
using AlasApp.Application.SurfScoresImport.Commands.ImportSurfScoresEvents;
using Microsoft.Extensions.DependencyInjection;

namespace AlasApp.Application.Common;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<IClock, SystemClock>();
        services.AddScoped<IRequestDispatcher, RequestDispatcher>();
        services.AddScoped<IRequestHandler<ListArticlesQuery, PagedResult<Articles.Models.ArticleSummaryDto>>, ListArticlesQueryHandler>();
        services.AddScoped<IRequestHandler<GetAdminSettingsQuery, AdminSettings.Models.AdminSettingsDto>, GetAdminSettingsQueryHandler>();
        services.AddScoped<IRequestHandler<UpdateAdminSettingsCommand, AdminSettings.Models.AdminSettingsDto>, UpdateAdminSettingsCommandHandler>();
        services.AddScoped<IRequestHandler<TestIntegrationCommand, AdminSettings.Models.IntegrationTestResultDto>, TestIntegrationCommandHandler>();
        services.AddScoped<IRequestHandler<GetArticleBySlugQuery, Articles.Models.ArticleDetailDto>, GetArticleBySlugQueryHandler>();
        services.AddScoped<IRequestHandler<CreateArticleCommand, Articles.Models.ArticleDetailDto>, CreateArticleCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateArticleCommand, Articles.Models.ArticleDetailDto>, UpdateArticleCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteArticleCommand, bool>, DeleteArticleCommandHandler>();
        services.AddScoped<IRequestHandler<ListAdminUsersQuery, IReadOnlyCollection<AdminUsers.Models.AdminUserDto>>, ListAdminUsersQueryHandler>();
        services.AddScoped<IRequestHandler<GetAdminUserByIdQuery, AdminUsers.Models.AdminUserDto>, GetAdminUserByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateAdminUserCommand, AdminUsers.Models.AdminUserDto>, CreateAdminUserCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateAdminUserCommand, AdminUsers.Models.AdminUserDto>, UpdateAdminUserCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteAdminUserCommand, bool>, DeleteAdminUserCommandHandler>();
        services.AddScoped<IRequestHandler<ListAdminRolesQuery, IReadOnlyCollection<AdminUsers.Models.RoleDto>>, ListAdminRolesQueryHandler>();
        services.AddScoped<IRequestHandler<GetDashboardQuery, Dashboard.Models.DashboardDto>, GetDashboardQueryHandler>();
        services.AddScoped<IRequestHandler<ListGalleriesQuery, IReadOnlyCollection<Galleries.Models.GallerySummaryDto>>, ListGalleriesQueryHandler>();
        services.AddScoped<IRequestHandler<GetGalleryBySlugQuery, Galleries.Models.GalleryDetailDto>, GetGalleryBySlugQueryHandler>();
        services.AddScoped<IRequestHandler<RegisterUserCommand, Auth.Models.RegisterResultDto>, RegisterUserCommandHandler>();
        services.AddScoped<IRequestHandler<LoginUserCommand, Auth.Models.LoginResultDto>, LoginUserCommandHandler>();
        services.AddScoped<IRequestHandler<RequestPasswordResetCommand, bool>, RequestPasswordResetCommandHandler>();
        services.AddScoped<IRequestHandler<ConfirmPasswordResetCommand, bool>, ConfirmPasswordResetCommandHandler>();
        services.AddScoped<IRequestHandler<ChangeUserPasswordCommand, bool>, ChangeUserPasswordCommandHandler>();
        services.AddScoped<IRequestHandler<LogoutUserCommand, bool>, LogoutUserCommandHandler>();
        services.AddScoped<IRequestHandler<ListMembershipsQuery, PagedResult<Memberships.Models.MembershipDto>>, ListMembershipsQueryHandler>();
        services.AddScoped<IRequestHandler<GetMembershipByIdQuery, Memberships.Models.MembershipDto>, GetMembershipByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateMembershipCommand, Memberships.Models.MembershipDto>, CreateMembershipCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateMembershipCommand, Memberships.Models.MembershipDto>, UpdateMembershipCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteMembershipCommand, bool>, DeleteMembershipCommandHandler>();

        services.AddScoped<IRequestHandler<ListCircuitsQuery, PagedResult<Circuits.Models.CircuitDto>>, ListCircuitsQueryHandler>();
        services.AddScoped<IRequestHandler<GetCircuitByIdQuery, Circuits.Models.CircuitDto>, GetCircuitByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateCircuitCommand, Circuits.Models.CircuitDto>, CreateCircuitCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateCircuitCommand, Circuits.Models.CircuitDto>, UpdateCircuitCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteCircuitCommand, bool>, DeleteCircuitCommandHandler>();
        services.AddScoped<IRequestHandler<ImportCircuitsCommand, BulkImports.Models.BulkImportResultDto>, ImportCircuitsCommandHandler>();

        services.AddScoped<IRequestHandler<ListEventsQuery, PagedResult<Events.Models.EventDto>>, ListEventsQueryHandler>();
        services.AddScoped<IRequestHandler<GetEventByIdQuery, Events.Models.EventDto>, GetEventByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateEventCommand, Events.Models.EventDto>, CreateEventCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateEventCommand, Events.Models.EventDto>, UpdateEventCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteEventCommand, bool>, DeleteEventCommandHandler>();
        services.AddScoped<IRequestHandler<ImportEventsCommand, BulkImports.Models.BulkImportResultDto>, ImportEventsCommandHandler>();

        services.AddScoped<IRequestHandler<ListCategoriesQuery, IReadOnlyCollection<Categories.Models.CategoryDto>>, ListCategoriesQueryHandler>();
        services.AddScoped<IRequestHandler<GetCategoryByIdQuery, Categories.Models.CategoryDto>, GetCategoryByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateCategoryCommand, Categories.Models.CategoryDto>, CreateCategoryCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateCategoryCommand, Categories.Models.CategoryDto>, UpdateCategoryCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteCategoryCommand, bool>, DeleteCategoryCommandHandler>();
        services.AddScoped<IRequestHandler<ImportCategoriesCommand, BulkImports.Models.BulkImportResultDto>, ImportCategoriesCommandHandler>();
        services.AddScoped<IRequestHandler<GetCategoryTariffsQuery, IReadOnlyCollection<CategoryTariffs.Models.CategoryTariffDto>>, GetCategoryTariffsQueryHandler>();
        services.AddScoped<IRequestHandler<UpsertCategoryTariffCommand, CategoryTariffs.Models.CategoryTariffDto>, UpsertCategoryTariffCommandHandler>();

        services.AddScoped<IRequestHandler<GetEventCategoriesQuery, EventCategories.Models.EventCategoryListDto>, GetEventCategoriesQueryHandler>();
        services.AddScoped<IRequestHandler<UpdateEventCategoriesCommand, EventCategories.Models.EventCategoryListDto>, UpdateEventCategoriesCommandHandler>();
        services.AddScoped<EventResultsWriter>();
        services.AddScoped<IRequestHandler<GetEventResultsQuery, IReadOnlyCollection<EventResults.Models.EventResultDto>>, GetEventResultsQueryHandler>();
        services.AddScoped<IRequestHandler<UpsertEventResultsCommand, IReadOnlyCollection<EventResults.Models.EventResultDto>>, UpsertEventResultsCommandHandler>();
        services.AddScoped<IRequestHandler<GetEventResultsRosterQuery, IReadOnlyCollection<EventResults.Models.EventResultRosterRowDto>>, GetEventResultsRosterQueryHandler>();
        services.AddScoped<IRequestHandler<ImportEventResultsCommand, BulkImports.Models.BulkImportResultDto>, ImportEventResultsCommandHandler>();
        services.AddScoped<IRequestHandler<GetPrizeDistributionQuery, EventResults.Models.PrizeDistributionDto>, GetPrizeDistributionQueryHandler>();
        services.AddScoped<IRequestHandler<ListCompetitorsQuery, PagedResult<Competitors.Models.CompetitorDto>>, ListCompetitorsQueryHandler>();
        services.AddScoped<IRequestHandler<GetCompetitorByIdQuery, Competitors.Models.CompetitorDto>, GetCompetitorByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateCompetitorCommand, Competitors.Models.CompetitorDto>, CreateCompetitorCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateCompetitorCommand, Competitors.Models.CompetitorDto>, UpdateCompetitorCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteCompetitorCommand, bool>, DeleteCompetitorCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateCompetitorLicenseCommand, Competitors.Models.CompetitorDto>, UpdateCompetitorLicenseCommandHandler>();
        services.AddScoped<IRequestHandler<GetCompetitorNotificationsQuery, Competitors.Models.NotificationPreferencesDto>, GetCompetitorNotificationsQueryHandler>();
        services.AddScoped<IRequestHandler<UpdateCompetitorNotificationsCommand, Competitors.Models.NotificationPreferencesDto>, UpdateCompetitorNotificationsCommandHandler>();
        services.AddScoped<IRequestHandler<GetCompetitorInscriptionsQuery, PagedResult<Competitors.Models.CompetitorInscriptionDto>>, GetCompetitorInscriptionsQueryHandler>();
        services.AddScoped<IRequestHandler<GetCompetitorPointsHistoryQuery, Competitors.Models.CompetitorPointsHistoryDto>, GetCompetitorPointsHistoryQueryHandler>();
        services.AddScoped<IRequestHandler<GetCompetitorCalendarQuery, IReadOnlyCollection<Competitors.Models.CompetitorCalendarEventDto>>, GetCompetitorCalendarQueryHandler>();
        services.AddScoped<IRequestHandler<ListCompetitorFinesQuery, IReadOnlyCollection<CompetitorFines.Models.CompetitorFineDto>>, ListCompetitorFinesQueryHandler>();
        services.AddScoped<IRequestHandler<CreateCompetitorFineCommand, CompetitorFines.Models.CompetitorFineDto>, CreateCompetitorFineCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateCompetitorFineCommand, CompetitorFines.Models.CompetitorFineDto>, UpdateCompetitorFineCommandHandler>();
        services.AddScoped<IRequestHandler<ListInscriptionsQuery, PagedResult<Inscriptions.Models.AdminInscriptionRowDto>>, ListInscriptionsQueryHandler>();
        services.AddScoped<IRequestHandler<GetInscriptionByIdQuery, Inscriptions.Models.InscriptionDto>, GetInscriptionByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreateInscriptionCommand, Inscriptions.Models.InscriptionDto>, CreateInscriptionCommandHandler>();
        services.AddScoped<IRequestHandler<UpdateInscriptionCommand, Inscriptions.Models.InscriptionDto>, UpdateInscriptionCommandHandler>();
        services.AddScoped<IRequestHandler<DeleteInscriptionCommand, bool>, DeleteInscriptionCommandHandler>();
        services.AddScoped<IRequestHandler<ListPaymentsQuery, PagedResult<Payments.Models.PaymentDto>>, ListPaymentsQueryHandler>();
        services.AddScoped<IRequestHandler<GetPaymentByIdQuery, Payments.Models.PaymentDto>, GetPaymentByIdQueryHandler>();
        services.AddScoped<IRequestHandler<CreatePaymentCommand, Payments.Models.PaymentDto>, CreatePaymentCommandHandler>();
        services.AddScoped<IRequestHandler<UpdatePaymentCommand, Payments.Models.PaymentDto>, UpdatePaymentCommandHandler>();
        services.AddScoped<IRequestHandler<InitiatePayPalOrderCommand, Payments.Models.PayPalOrderDto>, InitiatePayPalOrderCommandHandler>();
        services.AddScoped<IRequestHandler<CapturePayPalOrderCommand, Payments.Models.PaymentDto>, CapturePayPalOrderCommandHandler>();
        services.AddScoped<IRequestHandler<GetPaymentKpisQuery, Payments.Models.PaymentKpiDto>, GetPaymentKpisQueryHandler>();
        services.AddScoped<IRequestHandler<RequestBeachTokenCommand, Payments.Models.BeachTokenPendingDto>, RequestBeachTokenCommandHandler>();
        services.AddScoped<IRequestHandler<ApproveBeachTokenCommand, Payments.Models.BeachTokenAdminDto>, ApproveBeachTokenCommandHandler>();
        services.AddScoped<IRequestHandler<RejectBeachTokenCommand, Payments.Models.BeachTokenAdminDto>, RejectBeachTokenCommandHandler>();
        services.AddScoped<IRequestHandler<RedeemBeachTokenCommand, Payments.Models.BeachTokenRedeemResultDto>, RedeemBeachTokenCommandHandler>();
        services.AddScoped<IRequestHandler<ListBeachTokensQuery, Payments.Models.BeachTokenAdminListDto>, ListBeachTokensQueryHandler>();
        services.AddScoped<IRequestHandler<GetRankingQuery, Rankings.Models.RankingDto>, GetRankingQueryHandler>();
        services.AddScoped<IRequestHandler<ListRankingCategoriesQuery, IReadOnlyCollection<Rankings.Models.RankingCategoryAvailabilityDto>>, ListRankingCategoriesQueryHandler>();
        services.AddScoped<IRequestHandler<SyncSurfScoresCircuitCommand, Rankings.Models.SurfScoresSyncResultDto>, SyncSurfScoresCircuitCommandHandler>();
        services.AddScoped<IRequestHandler<ImportSurfScoresEventsCommand, SurfScoresImport.Models.SurfScoresImportResultDto>, ImportSurfScoresEventsCommandHandler>();
        services.AddScoped<IRequestHandler<GetPublicLiveStatusQuery, Live.Models.PublicLiveStatusDto>, GetPublicLiveStatusQueryHandler>();
        services.AddScoped<IRequestHandler<GetPublicSiteSettingsQuery, PublicSiteSettings.Models.PublicSiteSettingsDto>, GetPublicSiteSettingsQueryHandler>();

        return services;
    }
}
